import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/client/navbar";
import { createClient } from "@/utils/supabase/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const supabase = createClient();


type LayoutProps = {
  children: React.ReactNode;
};

export default async function Layout(props: LayoutProps) {
  const user = await supabase.auth.getUser();
console.log(user)
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {props.children}
      </body>
    </html>
  );
}
