import { NavBar } from "@/components/client/navbar";
import { getProfilesByUser } from "@/functions/getProfilesByUser";
import { getUser } from "@/functions/getUser";
import { createClient } from "@/utils/supabase/server";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ConditionalRender from "./conditionalRender";
import { CreateProfileForm } from "./createProfileForm";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const punycode = require("punycode/");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
};

export default async function Layout(props: LayoutProps) {
  const supabase = createClient();

  const user = await getUser();

  const profiles = user ? await getProfilesByUser(user.id) : [];

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar profiles={profiles} />
        {props.children}
        <ConditionalRender showWhen={profiles?.length === 0}>
          <CreateProfileForm />
        </ConditionalRender>
      </body>
    </html>
  );
}
