import { NavBar } from "@/components/client/navbar";
import { createClient } from "@/utils/supabase/server";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getUser } from "@/functions/getUser";
import { getProfilesByUser } from "@/functions/getProfilesByUser";
import { CreateProfile } from "./createProfile";
import ConditionalRender from "./conditionalRender";
import { Database } from "@/types/supabase";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


type LayoutProps = {
  children: React.ReactNode;
};

export default async function Layout(props: LayoutProps) {
  const supabase = createClient();
  
  const user = await getUser();

  const profiles = user ? await getProfilesByUser(user.id) : [];

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar profiles={profiles} />
        {props.children}
        <ConditionalRender showWhen={profiles?.length === 0}>
          <CreateProfile />
        </ConditionalRender>
      </body>
    </html>
  );
}
